### ISSUE TITLE
mobilenet model selection

### ISSUE THREAD

**Issue by geezacoleman** [Derekabc/CottonWeeds#1]
In `compute_sim.py` there's a reference to a models directory for the model path that isn't in the repository that I can see:
`EVAL_MODEL = '../../models/' + model_name + '_' + str(args.seeds) + ".pth"`

Did you use your model trained on the CottonWeeds dataset or the ImageNet-only model for the feature extraction and cosine similarity method as per the original repo (in `model_util.py`)?

**Comment by DongChen06** [comment]
Hi, thanks for your interest! I trained the model on our Cottonweeds dataset via transfer learning. In the following weeks, we will also make the trained models available. If you want to try them now, please feel free to reach out to me via email.

**Comment by geezacoleman** [comment]
Great thanks, nice paper/repo too! I'm hoping to extract features on our own dataset for cosine similarity comparison so might retrain the mobilenet with the data I have and then compare with the Imagenet version. 

If you get a chance, would recommend checking out [Weed-AI](https://weed-ai.sydney.edu.au/about), a project to maintain weeds image data in one spot with standardised metadata too.

**Comment by DongChen06** [comment]
Weed-AI is really a nice and meaningful project and hopes to see the academic paper soon.
